ALTER TABLE Test
 ADD chatType CHAR(10),
  ncharType NCHAR(10),
  guidType UNIQUEIDENTIFIER,
  intType INT,
  dobulbeType FLOAT(50),
  moneyTipe money,
  varcharType VARCHAR(10),
  nvarcharType NVARCHAR(10),
  boolType BIT,
  binaryType VARBINARY,
  decimalType DECIMAL(10,2),
  tipeType TIME, 
  dateType DATE,
  imageType IMAGE;
